inherit_from:
  - 'https://shopify.github.io/ruby-style-guide/rubocop.yml'

require: rubocop-performance

AllCops:
  TargetRubyVersion: 2.7
  Exclude:
    - 'vendor/bundle/**/*'
    - 'packaging/builds/**/*'

Metrics/MethodLength:
  Enabled: false

Layout/LineLength:
  Enabled: false

Lint/MissingSuper:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/StringLiteralsInInterpolation:
  Enabled: false
