name: theme-check

type: ruby

up:
  - ruby: 2.7.1
  - bundler

commands:
  check:
    desc: 'Check a theme'
    syntax:
      argument: file
    run: bundle exec theme-check
  test:
    syntax:
      argument: file
      optional: args...
    run: bundle exec rake test
  style:
    run: bundle exec rake rubocop
  liquid-server:
    run: bundle exec liquid-server
