name: ThemeCheck

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7
    - uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('Gemfile') }}
        restore-keys: ${{ runner.os }}-gems-
    - name: Install dependencies
      run: bundle install --jobs=3 --retry=3 --path=vendor/bundle
    - name: Run tests
      run: bundle exec rake
